---
default_config:

logger:
  default: info
  logs:
    custom_components.octopus_export: debug

# If you need to debug uncomment the line below
# Doc: https://www.home-assistant.io/integrations/debugpy/
# debugpy:
#   start: true
#   wait: false
